### ISSUE TITLE
The demo app has slowdown or crashes

### ISSUE THREAD

**Issue by jsamch** [Motsai/neblina-motiondemo-swift#3]
When running the app for some time, a slowdown happens and the app sometimes crashes.

**Comment by acourt** [comment]
I understood that it was the 3D animation that slowed down and not the app itself. I might be mistaken.

**Comment by jsamch** [comment]
The 3D animation slows down during usage.  I don't know why it happens.  Rotating the jet with the fingers while data is received can cause the app to crash or lock up.  I don't know of those elements are related.

**Comment by acourt** [comment]
My intuition tell me they are two separate issues.
